package io.floci.az.services.monitor;

import java.time.Duration;
import java.time.Instant;
import java.time.Period;
import java.time.format.DateTimeParseException;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

public class KqlEngine {

    private static final Pattern AGO_PATTERN = Pattern.compile("(?i)ago\\((\\d+)([a-zA-Z]+)\\)");
    private static final Pattern DATETIME_PATTERN = Pattern.compile("(?i)datetime\\(([^)]+)\\)");

    public static class KqlResult {
        public String tableName;
        public List<String> columns;
        public List<List<Object>> rows;

        public KqlResult(String tableName, List<String> columns, List<List<Object>> rows) {
            this.tableName = tableName;
            this.columns = columns;
            this.rows = rows;
        }
    }

    /**
     * Executes the given KQL query string over a list of raw log records.
     */
    public static KqlResult execute(String query, List<Map<String, Object>> records) {
        if (query == null || query.isBlank()) {
            throw new IllegalArgumentException("Query cannot be empty");
        }

        // Split pipeline by '|'
        String[] parts = query.split("\\|");
        String tableName = parts[0].trim();

        // Start with all records
        List<Map<String, Object>> currentRecords = new ArrayList<>(records);

        // Process operators in sequence
        List<String> projectedColumns = null;
        int limit = -1;

        for (int i = 1; i < parts.length; i++) {
            String operatorPart = parts[i].trim();
            if (operatorPart.startsWith("where ")) {
                String condition = operatorPart.substring(6).trim();
                currentRecords = evaluateWhere(currentRecords, condition);
            } else if (operatorPart.startsWith("project ")) {
                String colsStr = operatorPart.substring(8).trim();
                projectedColumns = Arrays.stream(colsStr.split(","))
                        .map(String::trim)
                        .collect(Collectors.toList());
            } else if (operatorPart.startsWith("take ") || operatorPart.startsWith("limit ")) {
                String limitStr = operatorPart.substring(operatorPart.startsWith("take ") ? 5 : 6).trim();
                try {
                    limit = Integer.parseInt(limitStr);
                } catch (NumberFormatException e) {
                    // ignore invalid limit
                }
            }
        }

        // Sort records descending by TimeGenerated by default (standard for logs)
        currentRecords.sort((r1, r2) -> {
            Instant t1 = parseTimeGenerated(r1.get("TimeGenerated"));
            Instant t2 = parseTimeGenerated(r2.get("TimeGenerated"));
            return t2.compareTo(t1);
        });

        // Apply limit if specified
        if (limit >= 0 && limit < currentRecords.size()) {
            currentRecords = currentRecords.subList(0, limit);
        }

        // Determine columns
        List<String> columns = projectedColumns;
        if (columns == null) {
            // If no project operator, collect all keys present in the records
            Set<String> allKeys = new LinkedHashSet<>();
            // Always put TimeGenerated first for convenience
            allKeys.add("TimeGenerated");
            for (Map<String, Object> rec : currentRecords) {
                allKeys.addAll(rec.keySet());
            }
            columns = new ArrayList<>(allKeys);
        }

        // Build rows
        List<List<Object>> rows = new ArrayList<>();
        for (Map<String, Object> rec : currentRecords) {
            List<Object> row = new ArrayList<>();
            for (String col : columns) {
                row.add(rec.get(col));
            }
            rows.add(row);
        }

        return new KqlResult(tableName, columns, rows);
    }

    private static List<Map<String, Object>> evaluateWhere(List<Map<String, Object>> records, String condition) {
        // Split by logical 'and' (case-insensitive)
        // Note: we do a simple split, assuming no complex nested queries or 'and' inside string literals.
        String[] andParts = condition.split("(?i)\\s+and\\s+");
        List<Map<String, Object>> filtered = new ArrayList<>(records);

        for (String part : andParts) {
            filtered = evaluateSingleCondition(filtered, part.trim());
        }

        return filtered;
    }

    private static List<Map<String, Object>> evaluateSingleCondition(List<Map<String, Object>> records, String cond) {
        String[] split = splitCondition(cond);
        if (split == null) {
            return records; // ignore/skip unparseable conditions
        }

        String op = split[0];
        String field = split[1].trim();
        String valExpr = split[2].trim();

        Object targetVal = parseValueExpression(valExpr);

        List<Map<String, Object>> result = new ArrayList<>();
        for (Map<String, Object> rec : records) {
            Object actualVal = rec.get(field);
            if (actualVal == null) {
                // Try case-insensitive lookup
                for (Map.Entry<String, Object> entry : rec.entrySet()) {
                    if (entry.getKey().equalsIgnoreCase(field)) {
                        actualVal = entry.getValue();
                        break;
                    }
                }
            }

            if (compare(actualVal, op, targetVal)) {
                result.add(rec);
            }
        }
        return result;
    }

    private static String[] splitCondition(String cond) {
        boolean inSingleQuote = false;
        boolean inDoubleQuote = false;
        for (int i = 0; i < cond.length(); i++) {
            char c = cond.charAt(i);
            if (c == '\'' && !inDoubleQuote) {
                inSingleQuote = !inSingleQuote;
            } else if (c == '"' && !inSingleQuote) {
                inDoubleQuote = !inDoubleQuote;
            }
            if (!inSingleQuote && !inDoubleQuote) {
                if (i < cond.length() - 1) {
                    String sub2 = cond.substring(i, i + 2);
                    if (sub2.equals("==") || sub2.equals("!=") || sub2.equals(">=") || sub2.equals("<=")) {
                        return new String[]{sub2, cond.substring(0, i), cond.substring(i + 2)};
                    }
                }
                String sub1 = cond.substring(i, i + 1);
                if (sub1.equals(">") || sub1.equals("<")) {
                    return new String[]{sub1, cond.substring(0, i), cond.substring(i + 1)};
                }
            }
        }
        return null;
    }

    private static Object parseValueExpression(String valExpr) {
        // Strip quotes if string literal
        if ((valExpr.startsWith("\"") && valExpr.endsWith("\"")) ||
            (valExpr.startsWith("'") && valExpr.endsWith("'"))) {
            return valExpr.substring(1, valExpr.length() - 1);
        }

        // Check if ago(...)
        Matcher agoMatcher = AGO_PATTERN.matcher(valExpr);
        if (agoMatcher.matches()) {
            int amount = Integer.parseInt(agoMatcher.group(1));
            String unit = agoMatcher.group(2).toLowerCase();
            Duration duration = switch (unit) {
                case "d", "day", "days" -> Duration.ofDays(amount);
                case "h", "hr", "hour", "hours" -> Duration.ofHours(amount);
                case "m", "min", "minute", "minutes" -> Duration.ofMinutes(amount);
                case "s", "sec", "second", "seconds" -> Duration.ofSeconds(amount);
                default -> Duration.ZERO;
            };
            return Instant.now().minus(duration);
        }

        // Check if datetime(...)
        Matcher dtMatcher = DATETIME_PATTERN.matcher(valExpr);
        if (dtMatcher.matches()) {
            String inner = dtMatcher.group(1).trim();
            if ((inner.startsWith("\"") && inner.endsWith("\"")) ||
                (inner.startsWith("'") && inner.endsWith("'"))) {
                inner = inner.substring(1, inner.length() - 1);
            }
            try {
                return Instant.parse(inner);
            } catch (DateTimeParseException e) {
                return Instant.EPOCH;
            }
        }

        // Check boolean
        if ("true".equalsIgnoreCase(valExpr)) return Boolean.TRUE;
        if ("false".equalsIgnoreCase(valExpr)) return Boolean.FALSE;

        // Check number
        try {
            return Double.parseDouble(valExpr);
        } catch (NumberFormatException e) {
            return valExpr;
        }
    }

    private static boolean compare(Object actual, String op, Object target) {
        if (actual == null) {
            return "!=".equals(op);
        }

        // If target is Instant (e.g. from ago() or datetime())
        if (target instanceof Instant targetInstant) {
            Instant actualInstant = parseTimeGenerated(actual);
            int comp = actualInstant.compareTo(targetInstant);
            return evalComparison(comp, op);
        }

        // If target is Number
        if (target instanceof Number targetNum) {
            double actualDouble;
            if (actual instanceof Number n) {
                actualDouble = n.doubleValue();
            } else {
                try {
                    actualDouble = Double.parseDouble(actual.toString());
                } catch (NumberFormatException e) {
                    return false;
                }
            }
            int comp = Double.compare(actualDouble, targetNum.doubleValue());
            return evalComparison(comp, op);
        }

        // Else treat as String / Boolean
        String actualStr = actual.toString();
        String targetStr = target.toString();

        if ("==".equals(op)) {
            return actualStr.equals(targetStr);
        } else if ("!=".equals(op)) {
            return !actualStr.equals(targetStr);
        } else {
            // String comparison for >, <, >=, <=
            int comp = actualStr.compareTo(targetStr);
            return evalComparison(comp, op);
        }
    }

    private static boolean evalComparison(int compResult, String op) {
        return switch (op) {
            case "==" -> compResult == 0;
            case "!=" -> compResult != 0;
            case ">"  -> compResult > 0;
            case "<"  -> compResult < 0;
            case ">=" -> compResult >= 0;
            case "<=" -> compResult <= 0;
            default   -> false;
        };
    }

    public static Instant parseTimeGenerated(Object val) {
        if (val == null) {
            return Instant.EPOCH;
        }
        if (val instanceof Instant inst) {
            return inst;
        }
        if (val instanceof Number num) {
            return Instant.ofEpochMilli(num.longValue());
        }
        try {
            return Instant.parse(val.toString());
        } catch (DateTimeParseException e) {
            return Instant.EPOCH;
        }
    }

    /**
     * Filters log records by the given timespan parameter.
     */
    public static List<Map<String, Object>> filterByTimespan(List<Map<String, Object>> records, String timespan) {
        if (timespan == null || timespan.isBlank()) {
            return records;
        }

        Instant start = null;
        Instant end = null;

        if (timespan.contains("/")) {
            String[] range = timespan.split("/", 2);
            start = parseTimespanInstant(range[0], true);
            end = parseTimespanInstant(range[1], false);
        } else {
            // Single ISO-8601 duration
            try {
                Duration duration;
                if (timespan.startsWith("P") && !timespan.contains("T")) {
                    // e.g. P1D, P7D
                    Period period = Period.parse(timespan);
                    duration = Duration.ofDays(period.getDays() + period.getMonths() * 30 + period.getYears() * 365);
                } else {
                    duration = Duration.parse(timespan);
                }
                start = Instant.now().minus(duration);
            } catch (Exception e) {
                // fallback to ignoring timespan if parsing fails
                return records;
            }
        }

        List<Map<String, Object>> filtered = new ArrayList<>();
        for (Map<String, Object> rec : records) {
            Instant time = parseTimeGenerated(rec.get("TimeGenerated"));
            boolean matches = true;
            if (start != null && time.isBefore(start)) {
                matches = false;
            }
            if (end != null && time.isAfter(end)) {
                matches = false;
            }
            if (matches) {
                filtered.add(rec);
            }
        }
        return filtered;
    }

    private static Instant parseTimespanInstant(String val, boolean isStart) {
        if (val == null || val.isBlank()) {
            return null;
        }
        if (val.startsWith("P")) {
            // Duration relative to now or boundary
            try {
                Duration duration = Duration.parse(val);
                return Instant.now().minus(duration);
            } catch (Exception e) {
                return null;
            }
        }
        try {
            return Instant.parse(val);
        } catch (DateTimeParseException e) {
            return isStart ? Instant.MIN : Instant.MAX;
        }
    }
}
