Args = --initialize-at-build-time=com.sun.jna \
       --initialize-at-run-time=com.github.dockerjava.transport.NamedPipeSocket,com.github.dockerjava.transport.NamedPipeSocket$Kernel32,com.github.dockerjava.core.util.CertificateUtils
